apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: gregmirabito1967/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gregmirabito1967/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: gregmirabito1967/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/tickets-depl.yaml
    - infra/k8s/tickets-mondo-depl.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/ingress-srv.yaml
profiles:
  - name: gcp
    build:
      googleCloudBuild:
        projectId: ticketing-dev-484614
        dockerImage: gcr.io/cloud-builders/docker
      artifacts:
        - image: us.gcr.io/ticketing-dev-484614/auth
          context: auth
          docker:
            dockerfile: Dockerfile
